// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqioLMo4A5iw-j9Ljqc5Sg5ff9cvEQSZo',
    appId: '1:701222721634:web:a503d3b3657a83c9ce593b',
    messagingSenderId: '701222721634',
    projectId: 'photo-social-network-fc4b0',
    authDomain: 'photo-social-network-fc4b0.firebaseapp.com',
    storageBucket: 'photo-social-network-fc4b0.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwRQOTgGB_rNdCz-kX3V87Y78QY6PHXYg',
    appId: '1:701222721634:android:c6a9d1d95616689ace593b',
    messagingSenderId: '701222721634',
    projectId: 'photo-social-network-fc4b0',
    storageBucket: 'photo-social-network-fc4b0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWfi7RHbIG6jxqdQbAQkHKp0cK4qAnceY',
    appId: '1:701222721634:ios:a087012e82682211ce593b',
    messagingSenderId: '701222721634',
    projectId: 'photo-social-network-fc4b0',
    storageBucket: 'photo-social-network-fc4b0.appspot.com',
    iosClientId:
        '701222721634-fp4jk6ildl3a2slll0oic31rc0qqv00f.apps.googleusercontent.com',
    iosBundleId: 'com.example.photoSocialNetwork',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCWfi7RHbIG6jxqdQbAQkHKp0cK4qAnceY',
    appId: '1:701222721634:ios:a087012e82682211ce593b',
    messagingSenderId: '701222721634',
    projectId: 'photo-social-network-fc4b0',
    storageBucket: 'photo-social-network-fc4b0.appspot.com',
    iosClientId:
        '701222721634-fp4jk6ildl3a2slll0oic31rc0qqv00f.apps.googleusercontent.com',
    iosBundleId: 'com.example.photoSocialNetwork',
  );
}
